In [1]:
from sqlalchemy import create_engine,inspect
import pandas as pd
from sqlalchemy import text
import psycopg2 
import numpy as np
import seaborn as sns

In [2]:
engine = create_engine(
    'postgresql+psycopg2://postgres:123456@111.186.56.196:5432/postgres',
    isolation_level="AUTOCOMMIT"
)

In [3]:
# 使用SQLAlchemy的inspect模块获取表和列信息
inspector = inspect(engine)

# 获取所有表的名称
tables = inspector.get_table_names()

# 遍历每个表并获取列名称
for table in tables:
    columns = inspector.get_columns(table)
    column_names = [column['name'] for column in columns]
    print(f"Table '{table}' has columns: {column_names}")

Table 'audio_data' has columns: ['Date', 'file_x', 'ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover', 'file_name', 'bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5', 'Chords', 'Key', 'Tempo_Estimates', 'Onsets', 'file_y', 'frequencies', 'LTS', 'MEANt_per_bin', 'VARt_per_bin', 'SKEWt_per_bin', 'KURTt_per_bin', 'LEQf_per_bin', 'ENRf_per_bin', 'BGNf_per_bin', 'SNRf_per_bin', 'Ht_per_bin', 'ACI_per_bin', 'ROU_per_bin', 'ACTspFract_per_bin', 'ACTspCount_per_bin', 'EVNspFract_per_bin', 'EVNspMean_per_bin', 'EVNspCount_per_bin', 'AGI_per_bin', 'file', 'isclipped', 'ismusic', 'isspeech', 'class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10', 'process', 'place', 'level']

In [4]:
def query_database(columns, table_name, engine, process=None, levels=None):
    # 构建 SQL 查询
    column_str = ', '.join([f'"{col}"' for col in columns])
    query = f'SELECT {column_str} FROM {table_name}'
    
    # 添加过滤条件
    conditions = []
    if process is not None:
        conditions.append(f"process = '{process}'")
    if levels is not None:
        level_str = ', '.join([str(level) for level in levels])  # 将 level 列表转换为字符串
        conditions.append(f"level IN ({level_str})")
    if conditions:
        query += ' WHERE ' + ' AND '.join(conditions)

    # 执行查询并加载数据到 DataFrame
    try:
        df = pd.read_sql_query(text(query), con=engine)
        return df
    except Exception as e:
        print("Error in query execution:", e)
        return None

In [5]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level', 'file']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")
df.to_pickle('fileinformation.pkl')

In [7]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level','ZCR', 'MEANt', 'VARt', 'SKEWt', 'KURTt', 'LEQt', 'BGNt', 'SNRt', 'MED', 'Ht', 'ACTtFraction', 'ACTtCount', 'ACTtMean', 'EVNtFraction', 'EVNtMean', 'EVNtCount', 'MEANf', 'VARf', 'SKEWf', 'KURTf', 'NBPEAKS', 'LEQf', 'ENRf', 'BGNf', 'SNRf', 'Hf', 'EAS', 'ECU', 'ECV', 'EPS', 'EPS_KURT', 'EPS_SKEW', 'ACI', 'NDSI', 'rBA', 'AnthroEnergy', 'BioEnergy', 'BI', 'ROU', 'ADI', 'AEI', 'LFC', 'MFC', 'HFC', 'ACTspFract', 'ACTspCount', 'ACTspMean', 'EVNspFract', 'EVNspMean', 'EVNspCount', 'TFSD', 'H_Havrda', 'H_Renyi', 'H_pairedShannon', 'H_gamma', 'H_GiniSimpson', 'RAOQ', 'AGI', 'ROItotal', 'ROIcover']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")

In [8]:
df.to_pickle('soundfeature_other.pkl')

In [9]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level','Chords', 'Key']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")

In [10]:
df.to_pickle('music_var_chordkey.pkl')

In [11]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level','Tempo_Estimates', 'Onsets']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")

In [12]:
df.to_pickle('music_var_tempo.pkl')

In [13]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level','bird_1', 'confidence_1', 'bird_2', 'confidence_2', 'bird_3', 'confidence_3', 'bird_4', 'confidence_4', 'bird_5', 'confidence_5','class_1', 'confidence_voice_1', 'class_2', 'confidence_voice_2', 'class_3', 'confidence_voice_3', 'class_4', 'confidence_voice_4', 'class_5', 'confidence_voice_5', 'class_6', 'confidence_voice_6', 'class_7', 'confidence_voice_7', 'class_8', 'confidence_voice_8', 'class_9', 'confidence_voice_9', 'class_10', 'confidence_voice_10']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")

In [14]:
df.to_pickle('class_var.pkl')

In [15]:
# 定义 SQL 查询，确保列名大小写正确
columns = ['Date', 'place','level','NDSI', 'ADI', 'ACI', 'RAOQ','AnthroEnergy','rBA','BioEnergy','BI','AEI','H_pairedShannon']
table_name = "audio_data"
# 使用 pandas 的 read_sql_query 函数直接加载数据到 DataFrame
df = query_database(columns, table_name, engine, process="origin")

In [16]:
df.to_pickle('basic_var.pkl')

In [17]:

df

,Date,place,level,NDSI,ADI,ACI,RAOQ,AnthroEnergy,rBA,BioEnergy,BI,AEI,H_pairedShannon
0,2023-09-23 22:30:00,CM,3,-0.976641,1.427496,339.87778,0.017437,49.610720,0.011817,0.586269,64.631180,0.576376,2.149657
1,2023-09-23 22:40:00,CM,3,-0.975455,1.652277,331.81220,0.017052,23.465150,0.012425,0.291551,63.759496,0.494264,2.229338
2,2023-09-23 22:50:00,CM,3,-0.973548,1.646109,318.25220,0.017265,37.451670,0.013403,0.501982,64.363555,0.483643,2.217352
3,2023-09-23 23:00:00,CM,3,-0.976475,1.727099,340.07318,0.015753,79.358536,0.011902,0.944564,64.090793,0.432585,2.231417
4,2023-09-23 23:10:00,CM,3,-0.958124,1.765791,341.09442,0.029282,32.733070,0.021386,0.700022,62.168898,0.401655,2.285993
...,...,...,...,...,...,...,...,...,...,...,...,...,...
606780,2023-09-23 21:40:00,CM,3,-0.990260,1.053934,317.22200,0.006799,57.510845,0.004894,0.281444,58.660398,0.706550,2.099177
606781,2023-09-23 21:50:00,CM,3,-0.974474,1.533733,314.16534,0.017237,24.191698,0.012928,0.312748,62.432953,0.550482,2.168922
606782,2023-09-23 22:00:00,CM,3,-0.988514,1.427808,342.92280,0.008000,126.445480,0.005776,0.730340,61.854805,0.575200,2.191768
606783,2023-09-23 22:10:00,CM,3,-0.983852,1.430760,366.28260,0.012319,116.097374,0.008140,0.944986,59.537996,0.563599,2.246934
606784,2023-09-23 22:20:00,CM,3,-0.925617,1.764649,350.53055,0.055152,17.916449,0.038628,0.692074,62.307008,0.411407,2.382040

In [18]:
df[df.place=="CM"]

,Date,place,level,NDSI,ADI,ACI,RAOQ,AnthroEnergy,rBA,BioEnergy,BI,AEI,H_pairedShannon
0,2023-09-23 22:30:00,CM,3,-0.976641,1.427496,339.87778,0.017437,49.610720,0.011817,0.586269,64.631180,0.576376,2.149657
1,2023-09-23 22:40:00,CM,3,-0.975455,1.652277,331.81220,0.017052,23.465150,0.012425,0.291551,63.759496,0.494264,2.229338
2,2023-09-23 22:50:00,CM,3,-0.973548,1.646109,318.25220,0.017265,37.451670,0.013403,0.501982,64.363555,0.483643,2.217352
3,2023-09-23 23:00:00,CM,3,-0.976475,1.727099,340.07318,0.015753,79.358536,0.011902,0.944564,64.090793,0.432585,2.231417
4,2023-09-23 23:10:00,CM,3,-0.958124,1.765791,341.09442,0.029282,32.733070,0.021386,0.700022,62.168898,0.401655,2.285993
...,...,...,...,...,...,...,...,...,...,...,...,...,...
606780,2023-09-23 21:40:00,CM,3,-0.990260,1.053934,317.22200,0.006799,57.510845,0.004894,0.281444,58.660398,0.706550,2.099177
606781,2023-09-23 21:50:00,CM,3,-0.974474,1.533733,314.16534,0.017237,24.191698,0.012928,0.312748,62.432953,0.550482,2.168922
606782,2023-09-23 22:00:00,CM,3,-0.988514,1.427808,342.92280,0.008000,126.445480,0.005776,0.730340,61.854805,0.575200,2.191768
606783,2023-09-23 22:10:00,CM,3,-0.983852,1.430760,366.28260,0.012319,116.097374,0.008140,0.944986,59.537996,0.563599,2.246934
606784,2023-09-23 22:20:00,CM,3,-0.925617,1.764649,350.53055,0.055152,17.916449,0.038628,0.692074,62.307008,0.411407,2.382040

In [19]:
pd.read_pickle("basic_var.pkl").to_csv("basic_var.csv")
pd.read_pickle("class_var.pkl").to_csv("class_var.csv")
pd.read_pickle("music_var_tempo.pkl").to_csv("music_var_tempo.csv")
pd.read_pickle("soundfeature_other.pkl").to_csv("soundfeature_other.csv")
pd.read_pickle("music_var_chordkey.pkl").to_csv("music_var_chordkey.csv")